templates:
  params:
    author-name: Kasshi K
    author-email: kasshi.4259.b.b@gmail.com
    category: Your Projects Category
    copyright: 'Copyright (c) 2021 chickbone'
    github-username: chickbone
  scm-init: git

system-ghc: false
install-ghc: false

ghc-options:
    # All packages
    "$locals": -Wall
    "$targets": -Werror
    "$everything": -O2 -haddock

