templates:
  author-name: Kasshi K
  author-email: kasshi.4259.b.b@gmail.com
  category: Your Projects Category
  copyright: 'Copyright (c) 2021 kousei kashihara'
  github-username: kasshiy
  params: null
  scm-init: git

system-ghc: true
install-ghc: false

ghc-options:
    # All packages
    "$locals": -Wall
    "$targets": -Werror
    "$everything": -O2 -haddock

